on:
  pull_request:
  push:
    branches-ignore:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Elixir
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.13.4
      - name: Set up deps
        run: mix deps.get
      - name: Run Test
        run: mix test
      - name: Export Test Coverage
        run: MIX_ENV=test mix coveralls.json
      - name: Push Test Coverage Data
        uses: codecov/codecov-action@v2
        with:
          files: ./cover/excoveralls.json
